src/generator.ts
src/install/installer.ts
src/tracemap/tracemap.ts
test/api/parallel.test.js
test/errors/no-subpath-recovery.test.js
test/errors/recovery.test.js

Trying to narrow down any error recovery issues.

Attempt to catch error recovery issue

---

package-lock.json
package.json
src/generator.ts

Resolves https://github.com/jspm/generator/issues/2

Fixup TS Output Signature

---

README.md

@jollytoad this has come out of a lot of your feedback, let me know if it seems to cover some of your initial questions ok?

Note overrides, conditions, exports

---

README.md
src/generator.ts

Allows `generator.install([...installs])`.

Support array installs

---

README.md
src/generator.ts
test/api/inputmap.test.js

Implements: https://github.com/jspm/generator/issues/33

Expose the "inputMap" option

---

src/generator.ts
src/install/installer.ts
src/providers/index.ts
src/providers/node.ts
src/providers/nodemodules.ts
src/trace/analysis.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/api/api.test.js

Includes various resolver fixes needed to get rollup-plugin-jspm tests all working.

fix: various resolver fixes

---

src/trace/resolver.ts

This updates JSPM core to the version with the new browser build running via rollup-plugin-jspm.

feat: JSPM core update with build

---

.github/workflows/ci.yml
.gitignore
package-lock.json
package.json
src/generator.ts
typedoc.json

This adds Typedoc support for documentation generation. Once hosted this will allow removing this information from the README for the website version instead.

docs: generate docs with typedoc

---

chompfile.toml
package-lock.json
package.json
test/html/lit.test.js

Updates to es-module-lexer@0.10.3 with asm.js memory stability.

deps: es-module-lexer@0.10.3

---

src/providers/jspm.ts
test/api/npmdep.test.js

Resolves bug https://github.com/jspm/generator/issues/54.

Handle npm latest tags

---

chompfile.toml
src/trace/tracemap.ts

Resolves https://github.com/jspm/generator/issues/150

perf: stop on dynamic import visit reentrancy

---

src/trace/resolver.ts

Resolves https://github.com/jspm/generator/issues/152.

fix: extend exists to handle more 400 codes

---

chompfile.toml
package.json
src/common/integrity.ts
src/generator-deno.ts
src/trace/cjs.ts
src/trace/resolver.ts
src/trace/ts.ts

This provides a dedicated Deno build which provides dependency injection for the dynamic imports. This ensures that the generator is compatible with deno bundle workflows.

Deno dependency injection

---

package.json
src/generator-deno.ts

This fixes the PR in https://github.com/jspm/generator/pull/154 which wasn't being properly tested.

fix: deno injection workflow

---

src/common/url.ts

Fixes baseURL detection in non-document environments.

fix: baseUrl in workers

---

src/providers/jspm.ts

This resolves the case in https://github.com/jspm/generator/issues/158, where prerelease version ranges might be downgraded if there was no stable version greater than the current prerelease version.

fix: prerelease downgrade bug

---

package-lock.json
package.json
src/install/installer.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/providers/deno.test.js

This fixes some edge cases around subpaths and custom installs. In particular, ensuring subpaths are fully propagated through the installer.

Subpath edge cases

---

src/providers/jspm.ts
test/api/notFound.test.js
test/utils/lookup.test.js

fix: add npm registry fallback to the lookupRange 

---

src/generator.ts

Resolves https://github.com/jspm/generator/issues/194.

fix: traceInstall as baseUrl-relative

---

package-lock.json
package.json

Fixes #203, tests fine, will see what a full upgrade does when I get a moment.

Upgrade babel dependencies.

---

chompfile.toml
package-lock.json
package.json
typedoc.json

See https://github.com/jspm/jspm.org/pull/22.

chore: rig up things for api doc generation on jspm.org

---

README.md
chompfile.toml
src/generator.ts
test/api/devdependencies.test.js
test/api/link.test.js
test/api/localpin.test.js
test/api/node.test.js
test/api/self-uninstall.test.js
test/api/traceinstall.test.js
test/html/multi.test.js
test/providers/deno.test.js
test/resolve/builtin-shim.test.js
test/resolve/ts.test.js

chore: alias traceInstall to link

---

src/generator.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/api/local/dep/package.json
test/api/local/pkg/package.json
test/api/localcjs.test.js
test/resolve/builtin-shim.test.js
test/resolve/chalk.test.js
test/resolve/legacy-main.test.js

feat: put local CJS tracing behind feature flag

---

src/generator.ts
test/api/install.test.js

chore: deprecate reinstall and support no-argument install

---

chompfile.toml
src/generator.ts
src/trace/resolver.ts

feat: auto-detect the default provider from input map when not given explicitly

---

src/generator.ts

See https://github.com/jspm/jspm/issues/173. At the moment the API to do this isn't exposed,
so we have no way of allowing html links in the CLI.

feat: add linkHtml method for linking the inline modules in a HTML file

---

src/generator.test.ts
src/generator.ts
src/install/lock.test.ts
src/install/lock.ts

feat: expose parseUrlPkg publically

---

README.md
src/generator.test.ts
src/generator.ts
src/install/installer.ts
src/providers/esmsh.ts
src/providers/index.test.ts
src/providers/index.ts
src/providers/jsdelivr.ts
src/providers/jspm.ts
src/providers/nodemodules.ts
src/providers/unpkg.ts
src/trace/resolver.ts
test/providers/esmsh.test.js

Fixes #269. Will post a PR updating the CLI as well.

feat: support esm.sh CDN

---

src/providers/jspm.ts

Ensure the exact URL is provided when there is a lookup error.

fix: easier lookup debugging

---

src/trace/analysis.ts
test/resolve/unused-cjs.test.js

This implements an alternative to https://github.com/jspm/generator/pull/394 resolving https://github.com/jspm/generator/issues/393.

fix: register regex backtracking

---

src/trace/resolver.ts

Resolves https://github.com/jspm/generator/issues/391

fix: better wording for nodemodules provider missing package

---

.github/workflows/ci.yml

ci: fix firefox tests

---

src/generator.ts

This fixes a bug with HTML preloading injection.

fix: html preloading injection
