jspm/generator

README.md
src/generator.ts

This supports a `subpaths` option in the `Install` object for installing multiple subpaths at the same time.

Support multiple subpaths

---

README.md
src/generator.ts

This makes the `"module"` condition a default option for `env` and also clarifies this condition in the readme.

Use module condition by default, clarify documentation

---

package.json

Encountered a small problem with types when trying generator in typescript project.  Types from `log` are missing in `dist` that's in `npm`
https://unpkg.com/browse/@jspm/generator@1.0.0-beta.2/dist/generator.d.ts

Copy types from log into dist

---

package.json
src/common/fetch-node.ts
src/install/installer.ts
src/install/package.ts
src/install/resolver.ts
src/providers/index.ts
src/providers/jsdelivr.ts
src/providers/jspm.ts
src/providers/nodemodules.ts
src/providers/skypack.ts
src/providers/unpkg.ts
src/tracemap/map.ts
test/api/localdeps.test.js
test/api/localdepsdirect.test.js
test/api/remotedep.test.js
test/providers/jsdelivr.test.js
test/providers/nodemodules.test.js
test/providers/unpkg.test.js
test/runMochaTests.js

This adds a `nodemodules` default provider which does a local node_modules lookup.
This actually works in the browser so long as the `node_modules/` fetch doesn't return a 404 (eg if it returns a listing page like a local server would). Otherwise it always works on the local file system too.
Tested with lit-element and seems like it works...!
Resolves https://github.com/jspm/generator/issues/21.
//cc @daKmoR

Support nodemodules provider

---

README.md
src/common/url.ts
src/generator.ts
src/tracemap/map.ts
test/api/rooturl.test.js

This resolves https://github.com/jspm/generator/issues/25, adding a `rootUrl` option which then takes precedence over the `mapUrl` option and forcing absolute paths.

Support rootUrl option, docs refactor

---

README.md
src/generator.ts
src/tracemap/map.ts
test/utils/fetch.test.js
test/utils/resolve.test.js

This adds two new utility methods:
1. Exposing the cached `fetch` hook via `import { fetch } from '@jspm/generator'`
2. Exposing the import map resolver via `generator.resolve()` as a sync function.
This will make it easier to construct build tools that want to wrap the generator.

Resolve method, expose fetch

---

README.md
src/generator.ts
src/install/package.ts
src/install/resolver.ts
src/providers/index.ts
src/providers/jsdelivr.ts
src/providers/jspm.ts
src/providers/nodemodules.ts
src/providers/skypack.ts
src/providers/unpkg.ts
test/providers/custom.test.js

This adds a new `customProviders` option which allows easily passing in custom provider definitions.
Includes tests and documentation.
//cc @vovacodes

feat: Support custom providers as an option

---

README.md
package.json
src/common/integrity.ts
src/generator.d.ts
src/generator.ts
src/install/installer.ts
src/install/package.ts
src/install/pjson.ts
src/providers/index.ts
src/providers/jspm.ts
src/providers/nodemodules.ts
src/trace/analysis.ts
src/trace/cjs.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/api/api.test.js
test/api/local/pkg/e.cjs
test/api/local/pkg/f.cjs
test/api/local/pkg/package.json
test/api/localcjs.test.js
test/api/traceinstall.test.js
tsconfig.json

This PR includes the following changes:
* CJS tracing is now supported for local `file:` URLs with Node.js compatible CJS semantics. This means it will be possible to generate import maps for Node.js apps using CJS modules.
* A new `generator.getAnalysis(url)` method for getting the internal analysis from the generator. At the moment this is just `{ staticDeps: string[], dynamicDeps: string[], format: 'commonjs' | 'esm' | 'system' }` but can be extended in future.
* The `getMapInstance` method previously implemented has been moved to just `generator.map` and no longer clones. This makes it easy to call the resolver via `generator.map.resolve('pkg')` or even modify the map via `generator.map.set()` etc per the @jspm/import-map API.
* `generator.traceInstall(specifier, parent)` has been …

CJS Tracing, traceInstall, getAnalysis

---

.github/workflows/ci.yml
package-lock.json
package.json
src/install/installer.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/resolve/builtin-shim.test.js
test/resolve/chalk.test.js
test/resolve/cjspkg/mod-shim.js
test/resolve/cjspkg/mod.js
test/resolve/cjspkg/node_modules/process/index.js
test/resolve/cjspkg/package.json

This fixes up builtin resolution, ensuring Node.js builtins are given precedence over normal dependencies resolutions to match the Node.js specification and also supporting builtin resolution for the nodemodules resolver.
Finally an exception is made for the `require('assert/')` pattern that is used to specially allow requiring npm:assert instead of getting the builtin which is an old Browserify trick. Supported here only for CJS to avoid polluting esm semantics just as in the Node.js ESM resolver itself.

feat: fixup builtin resolution

---

src/generator.d.ts
src/generator.ts
src/trace/analysis.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/resolve/ts.test.js
test/resolve/tspkg/dep.ts
test/resolve/tspkg/main.ts

This supports `format: 'typescript'` as a traced format in the analysis function, useful for determining if typescript is traced and which files are typescript.

feat: support typescript format

---

src/trace/resolver.ts
src/trace/tracemap.ts
test/api/self.test.js

This will add mappings into the generated import map for all symlinked resolutions to point to their actual path.
This will ensure symlinked paths only have a singular identity which will fix Node.js edge cases with symlinked node_modules etc. Because these are import map mappings, it would 100% support Deno too anyway.
There is also a `preserveSymlinks` resolver option that can be used to disable this feature if that turns out useful, but it is not currently exposed in the final generator options.

feat: apply realpath for file: URLs in traces

---

package-lock.json
package.json

`typescript` can be used here: https://github.com/jspm/generator/blob/765852b7edf7c7763de54c609922bd06a28860f0/src/trace/analysis.ts#L13.

fix: make typescript prod dependency

---

package-lock.json
package.json
src/common/fetch-deno.ts
src/trace/analysis.ts
src/trace/cjs.ts
src/trace/resolver.ts
src/trace/tracemap.ts
src/trace/ts.ts
test/api/self.test.js
test/deno.js
test/deno/babel.test.js
test/deno/self.test.js

This one has been a while in the making, but finally got there on it!
Replaces TypeScript with a Babel TypeScript transformer and gets Babel supported fully in the generator and in Deno.

feat: @babel/core Deno support

---

self-generate.js
src/trace/tracemap.ts
test/api/input-map-self.test.js
test/api/inputmap.test.js

This ensures that the "imports" of the inputMap, **always** override all deep dependency resolutions of any installs making them fully authoritative.

Input map override

---

src/providers/jspm.ts
test/api/self.test.js
test/providers/jspm-err.test.js

This ensures that all resolved packages support using the new JSPM build trigger API if their package builds are not yet present on the CDN, with polling.
In addition if the package build was a build error, the error log will be provided as an error message with an issue queue link for more understandable CDN build errors.
This is all jspm provider specific so only affects the provider implementation.

feat: trigger api builds for missing packages, report errored builds

---

src/providers/jspm.ts

Almost there but there were some encoding issues. Verified that the build request API is working correctly with this fix.

fix: fixup JSPM API build request format

---

src/trace/ts.ts

This adds JSX support **only when using TypeScript** per the fact that Deno supports it.

feat: support JSX for TS analysis

---

README.md
package-lock.json
src/generator.d.ts
src/generator.ts
src/install/installer.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/providers/jspm-err.test.js
test/providers/scopeprovider.test.js

This provides support for a custom provider map option allowing mapping eg package scopes to a custom provider such a nodemodules or a private registry.
Useful when using the JSPM CDN for public packages, but local node_modules / provider for private internal packages.

feat: custom provider mapping

---

src/common/fetch-deno.ts
src/common/fetch-native.ts

This implements a browser native fetch pool - stops the unreliable fetch errors that we've been getting on generator.jspm.io.

feat: browser native fetch pool

---

src/generator.ts
src/install/installer.ts
src/trace/tracemap.ts
test/api/deduping.test.js
test/api/local/react1/package.json
test/api/local/react1/react1.js
test/api/local/react2/package.json
test/api/local/react2/react2.js

This fixes the version deduping algorithm to ensure that in an application with two packages, one depending on `react: '16 || 17'` and another depending on `react: '16'` that you end up with one version of React at 16, instead of two separate versions of React.
This is achieved with a greedy resolution algorithm, by:
A) If `react: 16 || 17` is installed first, we install the highest version at 17. Then when `react: 16` is hit, we check all other packages using react and down grade them if the ranges accept that, allowing `react: 16` to be used.
B) If `react: 16` is installed first, we install that version. Then when `react: 16 || 17` is hit, we try install react 17 by upgrading all usages of react to this version, we then find out that we can't upgrade the `react: 16` range, so we cancel …

fix: version deduping

---

package-lock.json
package.json
src/generator.ts
src/install/installer.ts
test/api/localresolutions.test.js

This adds support for a `baseUrl` option separate from the `mapUrl` option, which allows setting a base for package install resolutions. Simplifies the `"resolutions"` field to more easily support relative package installs to a shared base. Also serves as the scope flattening base.

feat: baseUrl support

---

README.md
src/common/ipfs.ts
src/generator.ts

This updates the IPFS support to automatically select the best IPFS API to use by first trying the Brave browser API, falling back to the local IPFS Node, and with a better error message on failure.

Default to finding correct IPFS API

---

package.json
src/common/fetch-vscode.ts

This adds a fetch implementation for VSCode, so that the generator can be built and run in VSCode environments as an extension.

feat: fetch vscode support

---

package.json
rollup.config.js
src/common/fetch-vscode.ts
src/generator.ts
src/install/installer.ts
src/trace/resolver.ts

This adds the necessary fixes on top of https://github.com/jspm/generator/commit/77053c24c6bc2a1dad70232df8aaaa71e47d8472 to get the self-contained generator build running in VSCode environments (browser + electron).

feat: vscode support debugging

---

src/trace/tracemap.ts

This fix uses the logic that the require condition should always beat the import condition when both are resolved for the same scoping.
An alternative fix could be to rescope the parent specifically, and that fix would follow a similar code path.
@vovacodes perhaps you can verify if this works for you further?

Possible determinism fix for require / import

---

package.json
src/install/installer.ts
test/api/devdependencies.test.js
test/api/local/pkg/jquery.js
test/api/local/pkg/package.json

This adds local scoping for `"devDependencies"` to ensure that their resolutions are only followed when the current package scope matches the generator installer package scope.
Resolves https://github.com/jspm/generator/issues/84.

feat: devDependencies local scoping

---

package.json
src/html/analyze.ts
src/providers/jspm.ts

This fixes a couple of bugs with the HTML generation, namely:
* `<script type="module" src="main.js">` must resolve `./main.js` not the external package `main.js`.
* `fetchOpts` were not being provided to `ensureBuild` in the JSPM provider, causing an error

fix: HTML generation issues

---

.github/workflows/ci.yml
.gitmodules
package-lock.json
src/common/fetch-node.ts
src/generator.ts
test/deno/babel.test.js
test/deno/node.test.js
test/deno/self.test.js
test/html/inject.test.js
test/html/preload.test.js

This updates the fetch options to include brotli encoding, which is the fastest option for the JSPM CDN.

feat: use brotli encoding when possible

---

.github/workflows/ci.yml

This adds the Chomp GitHub action for much faster CI than the cargo install.

feat: Chomp action for faster CI

---

src/trace/resolver.ts

This fixes the browser loop in generation stopping nano-jsx generation from working.

fix: browser loop in generation

---

chompfile.toml
src/common/url.ts
src/generator.ts
src/install/installer.ts
src/install/lock.ts
src/trace/tracemap.ts
test/html/local/react.js
test/html/maps.test.js

This adds support for a `generator.getLock()` function for retrieving the lock file from an installer, as well as passing a `lock` option into the installer, resolving https://github.com/jspm/generator/issues/87.
In addition, the `htmlGenerate` method will now infer the lockfile and map as best as possible from the existing import map in the HTML.
The `freeze` and `latest` resolution options can now be passed to the generator initialization to determine how to resolve against the lockfile (don't change the resolutions for freeze, and always seek to use latest resolutions for latest).

feat: lockfile support, htmlGenerate lock inference

---

src/common/url.ts
src/generator.ts
src/html/analyze.ts
src/install/lock.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/html/inject.test.js
test/html/maps.test.js
test/html/preload.test.js

This fixes HTML integrity injection for all module scripts when using `integrity: true` for `htmlGenerate`, ensuring the integrity is comprehensively supported.
It also resolves https://github.com/jspm/generator/issues/105 in supporting local `inputMap` URL mappings.

fix: HTML integrity, URL mappings

---

package.json

The TypeScript `"types"` field fell out of sync, this updates to the new build structure.

fix: types field

---

chompfile.toml
src/trace/analysis.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/api/ignore.test.js
test/api/resolutions.test.js
test/api/self.test.js
test/html/indent.test.js
test/html/injectionpoint.test.js
test/html/inline.test.js
test/html/lit.test.js
test/html/maps.test.js
test/html/ws.test.js
test/resolve/object-inspect.test.js

This fixes support for imports like:
```json
{
"imports": {
"#impt": "external"
}
}
```
support in the generator where those resolutions then go through normal external package import resolution.

fix: imports field external resolutions

---

src/common/fetch-native.ts
src/install/installer.ts
src/providers/denoland.ts
src/providers/index.ts
src/trace/resolver.ts
test/providers/deno.test.js

This adds a Deno provider with very basic lookup support and package parsing. In addition a browser fix for the CORS error on Deno not founds is added as well.
Resolves https://github.com/jspm/generator/issues/138.

Deno provider

---

src/install/lock.ts

This fixes a bug introduced in 1.0.0-beta.32 where `extractLockAndMap` for `htmlGenerate` would incorrectly resolve top-level lockfile resolutions when there is no provider.

fix: extractLockAndMap bug

---

README.md
package-lock.json
package.json
src/common/url.ts
src/generator.ts
src/install/installer.ts
src/install/lock.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/api/devdependencies.test.js
test/api/localcjs.test.js
test/api/localdeps.test.js
test/api/localdepsdirect.test.js
test/api/localresolutions.test.js
test/api/reenv.test.js
test/api/remotedep.test.js
test/api/rooturl.test.js
test/api/traceinstall.test.js
test/providers/nodemodules.test.js
test/providers/scopeprovider.test.js
test/resolve/builtin-shim.test.js
test/resolve/chalk.test.js
test/resolve/nodemodules.test.js

This adds a new `generator.reinstall` method which can be used to reinstall all the `"imports"` of the import map.
In the test case, we have an import map created to the development export of React. We create a generator instance to the production condition with this inputMap, then use `generator.reinstall` to get the same versions of React and its dependencies, but with the exports conditions switched into production mode.
This also updates to v1 of the @jspm/import-map project and fixes a number of input map decomposition bugs.
Works very naturally based on the new architecture, thanks @JayaKrishnaNamburu for mentioning this missing function!

feat: reinstall method, fix destructuring case

---

src/generator.ts
src/install/installer.ts
src/install/package.ts
src/providers/denoland.ts
src/providers/index.ts
test/providers/deno.test.js

This adds support for first-class Deno installs via the recently-added Deno provider.
Specifically:
* `generator.install('deno:path')` corresponds to a stdlib install and will populate a versioned stdlib mapping for `path` to the Deno standard librariy.
* `generator.install('denoland:oak')` corresponds to a third-party Deno.land install and will populate the mapping similarly.
In addition a new `defaultRegistry` option is added as well as the ability for the `providers` object to provide registry mappings.
`defaultRegistry` applies the default registry for `generator.install('x')` to default to `generator.install('registry:x')` with the default obviously being `npm:`.
`providers` having custom `registry:` entries allows custom registry provider mappings via `new Generator({ providers: { …

feat: first-class Deno installs

---

src/generator.ts

This ensures es-module-shims itself is only removed from the DOM when using the es module shims option. Otherwise it is entirely left alone. Resolves https://github.com/jspm/generator/issues/161.

fix: esModuleShims false injection

---

package.json
src/generator.ts
src/providers/jspm.ts
test/api/update.test.js

This adds a new `generator.update('pkg')` API, taking package names (not specifiers like all other forms) to update. Resolves https://github.com/jspm/generator/issues/148.
The uninstall API has also been updated to support `pkg/` style shorthands to remove all subpaths of a package in one operation instead of needing to be explicitly enumerated.

feat: generator update API

---

src/generator.ts
src/install/installer.ts
src/install/lock.ts
src/install/package.ts
src/providers/denoland.ts
src/providers/index.ts
src/providers/jspm.ts
src/providers/node.ts
src/providers/nodemodules.ts
src/trace/resolver.ts
test/api/install-dedupe.test.js
test/api/update.test.js
test/html/breaks.test.js
test/html/emptymap.test.js
test/html/indent.test.js
test/html/inject.test.js
test/html/injectionpoint.test.js
test/html/inline.test.js
test/html/lit.test.js
test/html/maps.test.js
test/html/multi.test.js
test/html/preload.test.js
test/html/ws.test.js
test/providers/custom.test.js

This explicitly adds support for `generator.install('pkg@/subpath')` for installing the latest edge version of a dependency.
Resolves https://github.com/jspm/generator/issues/166.

feat: unstable installs via install(pkg@)

---

src/common/url.ts

Resolves https://github.com/jspm/generator/issues/168, ensuring that the baseURI hash and querystring are removed.

fix: strip baseuri hash and querystring

---

src/providers/jspm.ts
test/providers/jspm.cachefly.test.js

This adds support for an experimental CacheFly CDN layer, which can be opted-in to via the configuration:
```js
import { Generator } from '@jspm/generator';
const generator = new Generator({
defaultProvider: 'jspm.cachefly'
});
```
This will allow us to assess the performance of this CDN switch, before it applies to the entire CDN.

feat: cachefly CDN layer

---

README.md
chompfile.toml
package-lock.json
src/common/url.ts
src/generator.ts
src/install/installer.ts
src/trace/resolver.ts
src/trace/tracemap.ts
test/api/devdependencies.test.js
test/api/localpin.test.js
test/api/node.test.js
test/api/traceinstall.test.js
test/html/multi.test.js
test/providers/coremods/deno.js
test/providers/coremods/deno.notfound.js
test/providers/coremods/package.json
test/providers/deno.test.js
test/resolve/builtin-shim.test.js
test/test.html

This reinstates `generator.traceInstall`, instead of the recently attempted `generator.pin` name change.
`traceInstall` is then updated to always install traces into top-level imports rather than scopes, so it behaves like a full local install operator as opposed to making scopes that might be orphaned later on.
`traceInstall` effectively stops on bare specifiers, moving to scoped installs after that. This makes it useful for both adding local mappings (eg `generator.traceInstall('#local')` to add a local package.json "imports" map), and external (`generator.traceInstall('https://site.com/external.js')` - still populating `"imports"`).
Since `htmlInject` uses this internally this then fully matches the expectations of HTML tracing as well.

feat: reinstate trace install

---

package-lock.json
package.json

After removing `vscode` we no longer have any `npm audit` issues either, which
is nice.

chore: fix deprecated vscode dependency

---

package-lock.json
test/deno.js

Minor stuff done while digging into an importmap bug. Currently there's a test
failing because a newly released version of a transitive dependency is broken,
nothing we can do about it until they release a fix.

chore: fix dependency audit and silence deno tests

---

chompfile.toml
package-lock.json
package.json
tsconfig.json

Fixes #252. We need to do this in `@jspm/import-map` as well, it's suffering from
the same packaging issue.

fix: generate type declaration files and map to them in package.json

---

src/trace/analysis.ts
src/trace/cjs.ts
src/trace/tracemap.ts
test/resolve/unused-cjs.test.js
test/resolve/unusedcjspkg/cjs.js
test/resolve/unusedcjspkg/index.js
test/resolve/unusedcjspkg/package.json

See #259. Currently the generator is as strict as the Node.js resolver when it
comes to tracing CommonJS modules. For our purposes it only matters if the
traced CJS module uses CJS globals, as otherwise browser/deno runtimes can run
the module just fine in any case.

feat: only throw when tracing cjs modules that use cjs globals

---

src/install/installer.ts
test/api/install.test.js

See #226. Freeze actually already has the desired behaviour described there,
i.e. freeze will permit new locks to be added to the lockfile, but will never
bump any existing lock versions during an install, and will always use existing
locks for any install wherever possible. I've just added a test and some
comments on the `installTarget` function to make this clearer.

chore: add some tests around freeze installs and ensure they permit new locks

---

README.md

docs: update readme to reflect new provider names

---

src/generator.ts
src/install/installer.ts
test/api/freeze.test.js
test/api/local/freeze/package.json
test/test.html

Added a comment in `test/api/freeze.test.js` specifying the intended semantics
of the freeze flag and a bunch of tests pinning down all the cases:
```js
/**
* This test pins down the semantics of the "freeze" option on the generator.
*
* When enabled, the entire input map is treated as a strict lockfile, meaning
* no existing versions of any dependency will be changed by the generator. If
* there's a secondary lock for "react", for instance, then even a primary
* install will use that lock rather than latest. Freeze allows new dependencies
* to be added, however, if they have no existing locks.
*
* When freeze is combined with "resolutions", the custom resolutions always
* always take precedence over any of the freeze behaviour.
*
* When freeze is combined with "latest", the latest flag …
```

chore: pin down semantics of freeze with a bunch of test cases

---

src/providers/esmsh.ts
src/trace/resolver.ts
test/deno/esmsh.test.js
test/providers/esmsh.test.js

Adds a test that checks `deno`/`esm.sh` support. Found a few bugs along the
way, such as the fact that `esm.sh` serves files based on their _export_
subpath rather than their actual subpath on the filesystem.

fix: make sure esm.sh works with deno

---

src/providers/deno.ts

Fixes #272. Turns out we were already passing through `npm:XXX` specifiers in
the Deno provider, so I've just improved the error message. I think I was
stupidly testing it with `jspm install -p deno fresh`, which uses the `npm`
registry by default, whereas I should have done `jspm install -p deno denoland:fresh`.

fix: improve error message for deno lookup failures

---

src/generator.ts
test/html/preload-local.test.js

Fixes #277. It isn't technically a bug, as `generator.jspm.io` uses the old
`htmlGenerate` API, which doesn't take a `htmlUrl` as a property, and as a
result the output doesn't have properly rebased URLs. But it seems like a bad
gotcha anyway.

fix: propagate htmlUrl for deprected htmlGenerate

---

src/generator.ts
src/trace/resolver.ts

See https://github.com/jspm/jspm/issues/189. The logic for an install without
arguments in the generator is broken - we should be reinstalling top-level
_locks_, not top-level _pins_ (which can include custom mappings).

fix: install with no args should not reinstall custom mappings

---

src/install/installer.ts
src/providers/deno.ts
test/providers/deno.test.js

Fixes #289, or at least a first pass of a fix. This does the simplest thing for
now, which is to use the top-level imports for resolving a deno package's
secondary dependencies. This gets the `denoland:fresh/runtime.ts` example
working, for instance.

fix: hook into deno.json for deno dependencies

---

src/generator.ts
test/api/latest.test.js
test/api/urls.test.js

See #291. Plan is to hack arbitrary URL installation into the CLI for now, but
this custom mapping/alias issue was causing _that_ to fail too.

fix: handle aliases and custom mappings more sanely in reinstalls

---

src/providers/esmsh.ts
src/trace/resolver.ts

Seems like `esm.sh` returns 500s occasionally for what are actually `404`s,
when we're searching for package boundaries.

fix: don't throw on 500s from esm.sh

---

.github/dependabot.yml

Although  `dependabot` doesn't immediately trigger the update when `@jspm/import-map` is updated. This is good to have when a `minor` versions are missed. And when there is a change for `es-module-lexer` as well.

(chore): Add dependabot to check updates for generator and es-module-lexer

---

src/generator.ts
src/trace/analysis.ts
src/trace/resolver.ts
src/trace/tracemap.ts

Update resolver.ts to prevent crashing when encountering WASM modules

---

src/providers/node.ts
test/api/node.test.js

This fixes a bug where `fs/promises` wouldn't link correctly and throw the generation, due to it not being properly structured in the internal package resolution structure.

fix: fs/promises builtin linkage case

---

src/generator.ts

This adds a deprecation to the IPFS API configuration option, so that we can remove this feature in the next major.

Ipfs deprecate

---

src/generator.ts

When there's no process.env, the check above fails. This just guards it.

guard against a missing process.env (as in the browser)

---

src/common/wrapper.ts
src/generator.ts
test/html/esmsh.test.js

Resolves https://github.com/jspm/generator/issues/353 ensuring that the generated esm.sh URL for es-module-shims unwraps the wrapper.

fix: esmsh provider es module shims url

---

src/trace/resolver.ts

This fixes a failure case for resolution errors to ensure a resolve error is thrown instead of an internal error.

Resolve fail fix

---

src/trace/resolver.ts
src/trace/tracemap.ts
test/resolve/dayjs.test.js

Currently we only do extension searching in package subpath resolutions when the package is a CommonJS package, per the Node.js resolution rules.
This resolves https://github.com/jspm/generator/issues/355 in also performing subpath extension searching for extensions in addition when the subpath resolution is not resolved through exports.

feat: package subpath extension searching for both cjs and non-exports resolution

---

package-lock.json
package.json
src/generator-deno.ts
src/trace/ts.ts
test/test.html

Switches from using babel-plugin-import-assertions to babel-plugin-import-attributes.

fix: use babel plugin import attributes

---

src/generator.ts
src/providers/index.ts
src/providers/jspm.ts
test/providers/config.test.js

Adds a new `providerConfig` option to the generator which allows configuring providers through a `configure` provider hook.
For the JSPM provider, a `cdnUrl` configuration is added to customize the CDN URL.

Support provider configuration, with JSPM cdnUrl configuration

---

src/providers/esmsh.ts
src/providers/jsdelivr.ts
src/providers/jspm.ts
src/providers/skypack.ts
src/providers/unpkg.ts

This resolves https://github.com/jspm/generator/issues/379 ensuring that we always use the direct npm packument-style version lookups for non-JSPM providers.

fix: provider lookups to use standard npm packument

---

src/providers/esmsh.ts
src/providers/jsdelivr.ts
src/providers/jspm.ts
src/providers/skypack.ts
src/providers/unpkg.ts
src/trace/resolver.ts

The performance caching work done in https://github.com/jspm/generator/pull/380 created a version cache which wasn't being cleared between generator instantiations - and as a result, `api.jspm.io` isn't getting version updates.
This resolves that to ensure each new generator instance maintains its cache associated with the resolver context and that this cache is not shared between instances.

fix: clear version cache on each generator instantiation

---

package-lock.json
src/common/fetch.ts
src/common/wrapper.ts
src/generator.ts
src/providers/deno.ts
src/providers/esmsh.ts
src/providers/jspm.ts
src/providers/nodemodules.ts
src/trace/resolver.ts
test/npm-compatibility/install-pkg.test.js
test/npm-compatibility/install.test.js
test/npm-compatibility/update-pkg.test.js
test/npm-compatibility/update.test.js
test/perf/perf.test.js

This allows customizing the fetch function with a `setFetch` export from the generator:
```js
import { setFetch } from '@jspm/generator';
setFetch(myCustomFetchImplementation);
```

feat: allow customizing fetch with a setFetch export

---

src/trace/ts.ts
test/resolve/tspkg/main.ts
test/resolve/tspkg/types.ts

This disabled the tracing of `import type` statements entirely better supporting TS workflows.

fix: dont trace ts type imports

---

src/common/fetch-common.ts
src/common/fetch.ts
src/common/integrity.ts
src/generator.ts
src/providers/esmsh.ts
src/providers/index.ts
src/providers/jspm.ts
src/trace/analysis.ts
src/trace/resolver.ts
src/trace/tracemap.ts
src/trace/ts.ts
test/html/preload.test.js
test/perf/perf.test.js
test/providers/config.perf.test.js
test/resolve/cjspkg/browser-dep-exclude.js
test/resolve/cjspkg/browser-dep-include.js
test/resolve/cjspkg/browser.js
test/resolve/unused-cjs.test.js

While working on [this PR](https://github.com/jspm/generator/pull/400) I had to wrestle with my editor to not make a huge diff. It seems this project has `chomp prettier` configured, so I figured the intention was to use to prettier formatting. Raising this PR to help others not run into the same problem as I did when adding contributions to this project

Run `chomp prettier` on codebase

---

src/generator.ts
src/providers/esmsh.ts
src/providers/nodemodules.ts
src/trace/tracemap.ts
src/trace/ts.ts
test/html/esmsh.test.js
test/providers/esmsh.test.js

This fixes the pnpm support by changing the default generator option to support `preserveSymlinks`.
We also expose this option to the top-level generator options now so that it can be disabled when not desired.

fix: pnpm support via preserveSymlinks

---

src/trace/resolver.ts
test/api/update.test.js
test/providers/esmsh-root.test.js

This fixes the extract lock and deps for packages without exports better handling the package deconstruction in order to support updating multiple top-level imports mappings.
Resolves #409.

fix: update operation on packages without exports
